//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTransferStudentBrief_KH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentTransferStudentBrief_KH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SchoolList&gt;
        ///  &lt;School Name=&quot;私立時雨國中&quot; Code=&quot;011501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立板橋國中&quot; Code=&quot;014501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立重慶國中&quot; Code=&quot;014503&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立江翠國中&quot; Code=&quot;014504&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立中山國中&quot; Code=&quot;014505&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新埔國中&quot; Code=&quot;014506&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新莊國中&quot; Code=&quot;014507&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新泰國中&quot; Code=&quot;014508&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jh {
            get {
                return ResourceManager.GetString("jh", resourceCulture);
            }
        }
    }
}
